# Create a dockerfile with node image

# Use the official Node.js image as the base image
FROM node:14

# Create a directory to hold the application code inside the image
# This will be the working directory for your application
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run Nodeserver.js when the container launches
CMD [ "node", "Nodeserver.js" ]
